// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_notes is a generated GoMock package.
package mock_notes

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	entities "note-logger/internal/entities"
	reflect "reflect"
	time "time"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockRepository) Create(ctx context.Context, note *entities.Note) (*entities.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, note)
	ret0, _ := ret[0].(*entities.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockRepositoryMockRecorder) Create(ctx, note interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, note)
}

// ListBetween mocks base method
func (m *MockRepository) ListBetween(ctx context.Context, startTime, endTime time.Time) ([]*entities.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBetween", ctx, startTime, endTime)
	ret0, _ := ret[0].([]*entities.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBetween indicates an expected call of ListBetween
func (mr *MockRepositoryMockRecorder) ListBetween(ctx, startTime, endTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBetween", reflect.TypeOf((*MockRepository)(nil).ListBetween), ctx, startTime, endTime)
}

// Delete mocks base method
func (m *MockRepository) Delete(ctx context.Context, noteID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, noteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockRepositoryMockRecorder) Delete(ctx, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, noteID)
}
